### ISSUE TITLE
E-Checker does not catch spelling error in Analyte name

### ISSUE THREAD

**Issue by annikakj** [iedadata/EarthChemODM2TemplateReader#10]
Old E-Checker catches errors like this, where TiO2 was misspelled with a capital "I"

METHODS | E | 24 | TIO2 | is not IN Database

New  E-Checker does not flag this error.

**Comment by annikakj** [comment]
@jason they have to be: CO is NOT the same as Co

**Comment by jasonash** [comment]
@annikakj According to the enumerations in the new database, there is no CO.

Carbon Monoxide is CO1.

I will go ahead and add case sensitivity to the echecker.

**Comment by annikakj** [comment]
The old controlled vocab had the below, but I see your point in the new ECDB list. However, overall we should be replicating functionality of the old E-Checker as closely as possible as it was based on many years of file checking.

29 | CO |  
-- | -- | --
41 | Co | cobalt
30 | CO1 | carbon monoxide

**Comment by jasonash** [comment]
If we want to start changing the database schema, we should set up a meeting with @klehnert55 and @sparkji to discuss.

**Comment by sparkji** [comment]
@annikakj @klehnert55 Please confirm using Co represent cobalt, CO or CO1 represent carbon monoxide

**Comment by jasonash** [comment]
I have added a case sensitive analyte check with commit f5ef961b508f81ff8e6ff5d74c0f1da2b9564146
Please test.

**Comment by sparkji** [comment]
@annikakj If we use Co represent cobalt, CO represent carbon monoxide, that means we need caring about case sensitivity. Is there any similar case?

**Comment by annikakj** [comment]
@sparkji  I scanned through the variable list and it looks like any items like CO were update to be unique (e.g. CO1). As long as we are hand typing variables we need to keep spelling checking. Once we move to fill down menus in new Admin/data entry I think it takes care of itself
