### ISSUE TITLE
E-Checker does not catch missing table title

### ISSUE THREAD

**Issue by annikakj** [iedadata/EarthChemODM2TemplateReader#11]
@sparkji  I am assigning this to you first as I am very concerned as to the number of items the old E-Checker catches but the new one does not. Do we need to first look into how the new E-Checker was programmed?

Problem: new E-Checker does not flag a missing table title or number in Table_Titles tab.
In this file the table nr "3" was entered

 into TAB_IN_REF column in INCLUSIONS tab, but there was no table 3, nor table title for table 3 in the TABLE_TITLES Tab. Old E-Checker catches this error, new one does not.

**Comment by sparkji** [comment]
@jasonash please check the issue

**Comment by annikakj** [comment]
[3613.xlsx](https://github.com/iedadata/EarthChemODM2TemplateReader/files/2634208/3613.xlsx)

**Comment by jasonash** [comment]
A check for missing table_title or table_num has been added with commit d0a277d8e8729e600585b32f19b868384cecdd8c Please test.

**Comment by annikakj** [comment]
Confirming this is fixed.
