### ISSUE TITLE
Ignore addition sheet in echecker

### ISSUE THREAD

**Issue by sparkji** [iedadata/EarthChemODM2TemplateReader#12]
@jasonash  EarthD project is doing all of those tephra papers. They use current template but add additional sheet like 'tephra metadata'. They want to use echecker to check the template. Could you please add function to ignore checking these additional sheet in echecker?

**Comment by sparkji** [comment]
Thanks.

**Comment by kelseymarkey** [comment]
Confirmed with test EarthD File (1000.xls with added "Physical Info" tab).
