### ISSUE TITLE
E-Checker rejects He3_He4(R/Ra) without units

### ISSUE THREAD

**Issue by annikakj** [iedadata/EarthChemODM2TemplateReader#14]
@jasonash He3_He4(R/Ra) should be allowed to be entered without unit, as it is a ratio.
The old control lists and E-Checker allowed this.

**Comment by jasonash** [comment]
@annikakj Could you please provide the file you are checking so that I can test?

**Comment by annikakj** [comment]
Tested, issue is fixed.
