### ISSUE TITLE
Ref # 3603 stations not showing metadata

### ISSUE THREAD

**Issue by annikakj** [iedadata/EarthChemODM2TemplateReader#15]
@jasonash @sparkji http://ecstage.earthchem.org/station/701478 is not showing any metadata of map point.

**Comment by annikakj** [comment]
xls file can be found here:http://wiki.iedadata.org/display/GFG/PetDB+3600-3649

**Comment by annikakj** [comment]
same problem with ref 3604

**Comment by jasonash** [comment]
@annikakj I just loaded 3603 and 3604 and everything seems to be working fine. Did you try reloading the files?

**Comment by annikakj** [comment]
@jasonash I did not re-load them. I can try that. Can you explain why they need re-loading after I already got sheet loader message "Your file (3604.xls) was loaded successfully." when I initially loaded these files.

**Comment by annikakj** [comment]
I will try re-loading and refreshing view in Admin before looking in EC Stage.

**Comment by annikakj** [comment]
Files reloaded and checked.
