### ISSUE TITLE
ref 3582 loading error

### ISSUE THREAD

**Issue by annikakj** [iedadata/EarthChemODM2TemplateReader#16]
@jasonash Loading 3582.xls...

Notice: in /var/www/ec2odm2.earthchemportal.org/htdocs/api/EC2ODM2DatabaseClass.php on line 101 :: MDB2 Error: syntax error - _skipDelimitedStrings: [Error message: query with an unterminated text string specified] [Last executed query: DEALLOCATE PREPARE mdb2_statement_pgsql_7b54ca76ccc3ac3c73e6a624229c2a99] in /var/www/ec2odm2.earthchemportal.org/htdocs/api/func.php on line 62

.xls file is on Wiki.

**Comment by jasonash** [comment]
@annikakj This has been fixed with 426f50bb8486d139b7c8995400630c4365e01d25 Please try your upload again.

**Comment by annikakj** [comment]
File has been loaded.
