### ISSUE TITLE
SDVL:SEDIMENTARY not recognized by E-Checker

### ISSUE THREAD

**Issue by annikakj** [iedadata/EarthChemODM2TemplateReader#17]
@jasonash E-Checker rejects the Rock Type-Rock Class combination of SDVL SEDIMENTARY. The combination is listed in Admin Classification.

File to test: 3601.xls on Wiki.

**Comment by jasonash** [comment]
@annikakj  I have added SDVL SEDIMENTARY to the echecker. Please try your upload again.

**Comment by annikakj** [comment]
File passes E-checker now.
