### ISSUE TITLE
E-Checker does not flag repeat station name/id

### ISSUE THREAD

**Issue by annikakj** [iedadata/EarthChemODM2TemplateReader#18]
@jasonash  and @sparkji Repeated station names/ids are not flagged by new E-Checker. See file 3637.xls on WIki with annotation "Repeated stations IDs"

**Comment by jasonash** [comment]
@annikakj I have added a check for duplicate STATION_ID/STATION_NAME on STATIONS sheet with commit 6ccb94dee815e65f76158e1dd1f72356a1f16b8c. Please test.

**Comment by annikakj** [comment]
Tested on file 3637.xls. Stations now flagged as duplicates. Issue is resolved.
