### ISSUE TITLE
Missing Controlled Vocabulary in ODM2 for "variable" entries

### ISSUE THREAD

**Issue by jasonash** [iedadata/EarthChemODM2TemplateReader#2]
There seem to be several missing "variable" entries in the ODM2 controlled vocabulary that exist in PetDB.

The PetDB controlled vocabulary is located here:

http://wiki.iedadata.org/download/attachments/1441836/PetDB_CL_Y6Q4.xls

And these are the items that don’t appear to exist in the ODM2 controlled vocabulary.

ce136_ce142
delta_mo98
delta_s36
e_tl
hf177_hf178
hf179_hf177
nd144_nd146
nd146_nd142
nd146_nd145
nd148o_nd144o
os188_os192
perov
pb207_pb208
re185_re187
sm147_sm152
sr88_sr86
tl205_tl203
u230_th232_activity

**Comment by lulin-song** [comment]
@jasonash The data in EarthChemDB are old (maybe half year old). So it does not have all variables.

**Comment by jasonash** [comment]
@lulin-song Is there a more updated version of the database that I can use? Should I just add the missing values to the database? I just want to make sure that everything stays aligned for future development.

**Comment by lulin-song** [comment]
@jasonash The one you have is the latest. There are other controlled vocabularies which are added over time. Bai is working on updating EarthChemDB data to PetDB data Y6Q4 version. For the time being of your task, I think you can add them to your database but I not sure it is the good way to stay synced.
