### ISSUE TITLE
New Fractionation Correction Ratios

### ISSUE THREAD

**Issue by annikakj** [iedadata/EarthChemODM2TemplateReader#20]
Please add these FCORR RATIOS to allowed items:
On METHODS Sheet, FCORR RATIO "Cl37_Cl35" in column D is not a valid item name.
On METHODS Sheet, FCORR RATIO "O18_O16" in column E is not a valid item name.
On METHODS Sheet, FCORR RATIO "B11_B10" in column F is not a valid item name.

**Comment by jasonash** [comment]
@annikakj, I have added the FCORR RATIOS above. I don't have the file to test. Can you try your check again? Thanks.

**Comment by annikakj** [comment]
Confirming data entry sheet with these FRAC CORR now passes E-Checker
