### ISSUE TITLE
E-Checker/loader does not catch Expedition nrs lost in data loss

### ISSUE THREAD

**Issue by annikakj** [iedadata/EarthChemODM2TemplateReader#21]
New expedition was added to Admin
Subsequent data loss removed the expedition but E-Checker and loader still allow passage of the non-existent expedition nr.

**Comment by jasonash** [comment]
EChecker was checking for expedition number in action table but failed to limit on action_type_num. Peng recommended adding check for action_type_num constraint of 3,11,12,25. 

EChecker was altered to add check for action_type_num:

select count(*) from 
action
where
action_type_num = ANY (ARRAY[3, 11, 12, 25]) and
action.action_num =:expedition_num
