### ISSUE TITLE
Loader does not change corrected lat/longs for ref 3079

### ISSUE THREAD

**Issue by annikakj** [iedadata/EarthChemODM2TemplateReader#4]
Ref nr 3079 was discovered to have flipped lat/longs (Lat was in long column and vice versa). The  3079.xls sheet was corrected and reloaded, but the stations still have old lat/longs

Correct latitudes are values of 23...North and longitudes of 58... East.

**Comment by annikakj** [comment]
http://wiki.iedadata.org/pages/viewpageattachments.action?pageId=14583675&sortBy=date&highlight=3079.xls&

**Comment by annikakj** [comment]
Has there been progress on this?

**Comment by jasonash** [comment]
@annikakj Peng was supposed to edit this station manually. The loader will usually replace the station with the updated information, but there must have already been samples assigned to it from another reference. I don't have access to the database, so I can't be sure.

**Comment by annikakj** [comment]
@Jason, there are no samples associated with these stations from another reference.
We do need the capability to have lat/longs updated for a singular set of stations like this by re-loading the paper (as was done).

Annika

**Comment by jasonash** [comment]
@annikakj Yes, I understand. Unfortunately, I no longer have access to the database so it is nearly impossible for me to investigate further.

**Comment by sparkji** [comment]
fixed
