### ISSUE TITLE
Loader does not flag file without any lat/longs

### ISSUE THREAD

**Issue by annikakj** [iedadata/EarthChemODM2TemplateReader#5]
@sparkji File with blank cells in Station tab columns for Latitude On, Longitude On, Lat_Long_Precision passed both E-Checker and Loader without flagging error

**Comment by jasonash** [comment]
Fixed with b177592b6a30e6d2163a87d23ce440fd676497ab

**Comment by annikakj** [comment]
tested, problem is fixed
