### ISSUE TITLE
E-Checker does not catch misspelled column heading in STATIONS tab

### ISSUE THREAD

**Issue by annikakj** [iedadata/EarthChemODM2TemplateReader#6]
@sparkji Geolocation header that should be VOLCANIC_ARC was misspelled as VOLCANICPARC but E-Checker did not flag this as an error.

**Comment by jasonash** [comment]
Fixed with 4452fe7f22ad094e438b006fed5a093f8ec4f7bc. Please test.

**Comment by annikakj** [comment]
@jasonash  it is now giving error on the column heading "VOLCANO" which is a valid word.

**Comment by jasonash** [comment]
@annikakj OK, please try again.

**Comment by annikakj** [comment]
Confirming that it is fixed

**Comment by annikakj** [comment]
@jasonash can you please check all column headings in current sheet. Now the next one over is causing an error.

**Comment by jasonash** [comment]
@annikakj when you say "the next one over", what does that mean? Can you please tell me which column is not working now? I have included all of the columns that appear in several sheets that I have, but it looks like there might be some missing.

**Comment by annikakj** [comment]
@jasonash  all items in this list must be allowed:http://129.236.29.108:7001/petdbWeb/search/set_geo_name.jsp

**Comment by jasonash** [comment]
@annikakj  OK, I have verified that the following columns are being checked on the stations sheet:


```
AREA_ON_RIDGE
BACK-ARC_BASIN
CINDER_CONE
COUNTRY
CRATON
CRUISE NAME
DIATREME
ELEVATION_MAX
ELEVATION_MAX
ELEVATION_MIN
ELEVATION_MIN
EXPEDITION_NUM
FOCUS_SITE
FOSSIL_RIDGE
FRACTURE_ZONE
ISLAND_GROUP
LAND_OR_SEA
LARGE_IGNEOUS_PROVINCE
LAT_LONG_PRECISION
LATITUDE OFF
LATITUDE ON
LEG
LOCATION_COMMENT
LONGITUDE OFF
LONGITUDE ON
MAAR
MOBILE_BELT
NAVIGATION METHOD
OCEAN
OCEAN
OCEANIC_PLATEAU
OCEANIC_RIDGE
OCEAN_ISLAND
OCEAN_BASIN
OPHIOLITE
OROGENIC_BELT
PLATEAU
RIDGE_SECTION
RIFT
SAMPLING TECHNIQUE
SAMPLING_DATE
SEA
SEAMOUNT
SEAMOUNT_CHAIN
SPREADING_CENTER
STATION_COMMENT
STATION_ID
STATION_NAME
TECTONIC_SETTING
VOLCANIC_ARC
VOLCANIC_FIELD
VOLCANIC_PROVINCE
VOLCANO
```

Please test again.

**Comment by annikakj** [comment]
Confirming other headings now checked
