### ISSUE TITLE
E-Checker does not flag incorrect Rock type:Rock class combination in SAMPLES

### ISSUE THREAD

**Issue by annikakj** [iedadata/EarthChemODM2TemplateReader#7]
@sparkji An incorrect combination or IVM: BASALTIC ANDESITE (should be IVI: BASALTIC ANDESITE) was entered, but E-Checker did not flag this as an error.

**Comment by annikakj** [comment]
This problem has not yet been fixed. Is there an update on timeline?

**Comment by jasonash** [comment]
@annikakj I will work on it soon.

**Comment by jasonash** [comment]
This has been fixed with e76a403ae0e1fae234ccccaac5de341c0da4e30d Please test.

**Comment by annikakj** [comment]
Confirming that files now are flagged if RC_RT combination is not correct.
