### ISSUE TITLE
Deploy a new instance for debugging and testing

### ISSUE THREAD

**Issue by sparkji** [iedadata/EarthChemODM2TemplateReader#8]
@jasonash, could you please deploy another sheetloader instance, but point to development database for debugging and testing?
I think this will make you work efficiently and comfortable. The dev server located LDEO, you could access it using graphical client like RazorSQL or pgadmin, etc.

dev database
host:dev-ecdb-vm.earthchem.org
port :5432
dbname:ecdb_v1
user: ecdb_dev
pwd: not changed

**Comment by jasonash** [comment]
@sparkji A new instance of the template loader has been deployed to: http://devec2odm2.earthchemportal.org

**Comment by sparkji** [comment]
Great!
Thanks
