### ISSUE TITLE
Loading error ref 3599

### ISSUE THREAD

**Issue by annikakj** [iedadata/EarthChemODM2TemplateReader#9]
@jasonash Loading 3599.xls...

Notice: in /var/www/ec2odm2.earthchemportal.org/htdocs/api/EC2ODM2DatabaseClass.php on line 101 :: MDB2 Error: syntax error - prepare: [Error message: Unable to create prepared statement handle] [Last executed query: DEALLOCATE PREPARE mdb2_statement_pgsql_947816fcfb135fc65c6ad1979608929e] [Native message: ERROR: syntax error at end of input LINE 20: , LOC$5 ^] in /var/www/ec2odm2.earthchemportal.org/htdocs/api/func.php on line 62

**Comment by jasonash** [comment]
@annikakj I need the file you were trying to load in order to work on this.

**Comment by annikakj** [comment]
Indeed, location info was shifted one column to the left. Thank you. Fixed .xls, ran loader. Issue has been fixed.
